### ISSUE TITLE
提问：为什么firefox加载错误？

### ISSUE THREAD

**Issue by qingdxy** [psychelzh/MachineLearning-Workshop#1]
[图片]如图所示。X-mining的软件显示firefox的加载找不到文件。但是其实可以从地址手动打开Jupyter lab。不知道这个caff算不算install成功了？

[I 22:15:57.739 LabApp] The Jupyter Notebook is running at:
[I 22:15:57.740 LabApp] http://localhost:8891/?token=8ba15249f9b5a2bb2cb0097affa01d42a75f61655dd50871
[I 22:15:57.740 LabApp]  or http://127.0.0.1:8891/?token=8ba15249f9b5a2bb2cb0097affa01d42a75f61655dd50871
[I 22:15:57.741 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:15:57.755 LabApp]

    To access the notebook, open this file in a browser:
        file:///home/xiyu/.local/share/jupyter/runtime/nbserver-16-open.html
    Or copy and paste one of these URLs:
        http://localhost:8891/?token=8ba15249f9b5a2bb2cb0097affa01d42a75f61655dd50871
     or http://127.0.0.1:8891/?token=8ba15249f9b5a2bb2cb0097affa01d42a75f61655dd50871
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default

(firefox:21): dconf-CRITICAL **: 22:15:58.783: unable to create directory '/home/xiyu/.cache/dconf': Permission denied.  dconf will not work properly.

(firefox:21): dconf-CRITICAL **: 22:15:58.784: unable to create directory '/home/xiyu/.cache/dconf': Permission denied.  dconf will not work properly.

(firefox:21): dconf-CRITICAL **: 22:15:58.823: unable to create directory '/home/xiyu/.cache/dconf': Permission denied.  dconf will not work properly.

**Comment by psychelzh** [comment]
I guess that there must be a popup window like this:

![TIM图片20190727223756](https://user-images.githubusercontent.com/13306020/61995755-3cfd8300-b0bf-11e9-95a7-5fa25a313135.png)

One possible solution is to execute this command on `Ubuntu` (inspired by [this thread](https://ubuntuforums.org/showthread.php?t=2301995)):

```bash
sudo chown -R $USER:$USER ~/.cache
```

**Comment by psychelzh** [comment]
If you want to check whether `caffe` is correctly installed, you could simply enter `python3` on Ubuntu terminal, and try `import caffe` in python.

**Comment by qingdxy** [comment]
so true. After adding the code, the error is no longer exist. thank you for beautifully solve the problem.




------------------ 原始邮件 ------------------
发件人: "Liang Zhang"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 晚上10:40
收件人: "psychelzh/MachineLearning-Workshop"<MachineLearning-Workshop@noreply.github.com>;
抄送: "番茄及其衍生物重度爱好者"<965541857@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [psychelzh/MachineLearning-Workshop] 提问：为什么firefox加载错误？ (#1)




I guess that there must be a popup window like this:
 

 
One possible solution is to execute this command on Ubuntu:
 sudo chown -R $USER:$USER ~/.cache

**Comment by qingdxy** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-6e7bb19bc708> in <module>()
----> 1 import caffe

/usr/lib/python3/dist-packages/caffe/__init__.py in <module>()
----> 1 from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
      2 from ._caffe import init_log, log, set_mode_cpu, set_mode_gpu, set_device, Layer, get_solver, layer_type_list, set_random_seed, solver_count, set_solver_count, solver_rank, set_solver_rank, set_multiprocess, has_nccl
      3 from ._caffe import __version__
      4 from .proto.caffe_pb2 import TRAIN, TEST
      5 from .classifier import Classifier

/usr/lib/python3/dist-packages/caffe/pycaffe.py in <module>()
     13 from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
     14         RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
---> 15 import caffe.io
     16 
     17 import six

/usr/lib/python3/dist-packages/caffe/io.py in <module>()
      1 import numpy as np
----> 2 import skimage.io
      3 from scipy.ndimage import zoom
      4 from skimage.transform import resize
      5 

/usr/local/lib/python3.6/dist-packages/skimage/__init__.py in <module>()
    133                              img_as_bool,
    134                              dtype_limits)
--> 135     from .data import data_dir
    136     from .util.lookfor import lookfor
    137 

/usr/local/lib/python3.6/dist-packages/skimage/data/__init__.py in <module>()
     14 from .._shared._warnings import expected_warnings, warn
     15 from ..util.dtype import img_as_bool
---> 16 from ._binary_blobs import binary_blobs
     17 from ._detect import lbp_frontal_face_cascade_filename
     18 

/usr/local/lib/python3.6/dist-packages/skimage/data/_binary_blobs.py in <module>()
      1 import numpy as np
----> 2 from ..filters import gaussian
      3 
      4 
      5 def binary_blobs(length=512, blob_size_fraction=0.1, n_dim=2,

/usr/local/lib/python3.6/dist-packages/skimage/filters/__init__.py in <module>()
      1 from .lpi_filter import inverse, wiener, LPIFilter2D
----> 2 from ._gaussian import gaussian
      3 from .edges import (sobel, sobel_h, sobel_v,
      4                     scharr, scharr_h, scharr_v,
      5                     prewitt, prewitt_h, prewitt_v,

/usr/local/lib/python3.6/dist-packages/skimage/filters/_gaussian.py in <module>()
      1 from collections.abc import Iterable
      2 import numpy as np
----> 3 from scipy import ndimage as ndi
      4 
      5 from ..util import img_as_float

/usr/lib/python3/dist-packages/scipy/ndimage/__init__.py in <module>()
    159 from __future__ import division, print_function, absolute_import
    160 
--> 161 from .filters import *
    162 from .fourier import *
    163 from .interpolation import *

/usr/lib/python3/dist-packages/scipy/ndimage/filters.py in <module>()
     35 from . import _ni_support
     36 from . import _nd_image
---> 37 from scipy.misc import doccer
     38 from scipy._lib._version import NumpyVersion
     39 

/usr/lib/python3/dist-packages/scipy/misc/__init__.py in <module>()
     51 from .common import *
     52 from numpy import who, source, info as _info
---> 53 from scipy.interpolate._pade import pade
     54 from scipy.special import comb, factorial, factorial2, factorialk, logsumexp
     55 

/usr/lib/python3/dist-packages/scipy/interpolate/__init__.py in <module>()
    174 from __future__ import division, print_function, absolute_import
    175 
--> 176 from .interpolate import *
    177 from .fitpack import *
    178 

/usr/lib/python3/dist-packages/scipy/interpolate/interpolate.py in <module>()
     19 
     20 import scipy.linalg
---> 21 import scipy.special as spec
     22 from scipy.special import comb
     23 

/usr/lib/python3/dist-packages/scipy/special/__init__.py in <module>()
    646 from .orthogonal import *
    647 from .spfun_stats import multigammaln
--> 648 from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
    649 from .lambertw import lambertw
    650 from ._spherical_bessel import (spherical_jn, spherical_yn, spherical_in,

/usr/lib/python3/dist-packages/scipy/special/_ellip_harm.py in <module>()
      5 
      6 from ._ufuncs import _ellip_harm
----> 7 from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
      8 
      9 

scipy/special/_ellip_harm_2.pyx in init scipy.special._ellip_harm_2 (scipy/special/_ellip_harm_2.c:8501)()

/usr/lib/python3/dist-packages/scipy/integrate/__init__.py in <module>()
     57 from .quadpack import *
     58 from ._ode import *
---> 59 from ._bvp import solve_bvp
     60 
     61 __all__ = [s for s in dir() if not s.startswith('_')]

/usr/lib/python3/dist-packages/scipy/integrate/_bvp.py in <module>()
      8 
      9 from scipy.sparse import coo_matrix, csc_matrix
---> 10 from scipy.sparse.linalg import splu
     11 from scipy.optimize import OptimizeResult
     12 

/usr/lib/python3/dist-packages/scipy/sparse/linalg/__init__.py in <module>()
    111 from __future__ import division, print_function, absolute_import
    112 
--> 113 from .isolve import *
    114 from .dsolve import *
    115 from .interface import *

/usr/lib/python3/dist-packages/scipy/sparse/linalg/isolve/__init__.py in <module>()
      4 
      5 #from info import __doc__
----> 6 from .iterative import *
      7 from .minres import minres
      8 from .lgmres import lgmres

/usr/lib/python3/dist-packages/scipy/sparse/linalg/isolve/iterative.py in <module>()
      8 
      9 from scipy.sparse.linalg.interface import LinearOperator
---> 10 from scipy._lib.decorator import decorator
     11 from .utils import make_system
     12 from scipy._lib._util import _aligned_zeros

ModuleNotFoundError: No module named 'scipy._lib.decorator'


sorry, I still can not import caffe in jupyter lab.

**Comment by psychelzh** [comment]
@qingdxy Please open another issue to track this error. Thanks!
