### ISSUE TITLE
这个教程里的apt安装方式已经失效了

### ISSUE THREAD

**Issue by billzhen870** [psychelzh/MachineLearning-Workshop#4]
在[Google Groups](https://groups.google.com/g/caffe-users/c/laTmJMQ-Ma8)里有人说
>Caffe is no longer maintained, so new Ubuntu releases don't get precompiled apt packages anymore (actually, the code was not updated since 2015, so it didn't work on earlier Ubuntu versions either - but that's another story...). The only way is to compile it yourself. A while ago, I bundled my insights on this process in an installation guide you can find here: [https://github.com/Totemi1324/caffe-installation-guide](https://github.com/Totemi1324/caffe-installation-guide) Give it a try to see if it helps! I'm here for questions if you are struggling with something.
麻烦修改一下，提醒已经失效了

**Comment by psychelzh** [comment]
可能现在最好的办法是用docker，请参考[官方的caffe的docker使用指南](https://github.com/BVLC/caffe/tree/master/docker). 只要安装好docker，使用起来也很方便的。
